// Generated by Wrangler by running `wrangler types`
// EXEC_API_KEY is a Wrangler secret (see .dev.vars.example / `wrangler secret put`).

interface Env {
	Sandbox: DurableObjectNamespace<import("./src/index").Sandbox>;
	/** Shared secret for Authorization: Bearer on POST /api/exec */
	EXEC_API_KEY: string;
}
